import { useState } from 'react'
import ProjectLinks from './ProjectLinks.jsx'
import '../../agri-availability.css'

const tabs = [
  ['System', ['React Client', 'Pages · Components · Context API', 'HTTP requests through Axios · Socket.IO connection'], ['Node.js and Express API', 'Authentication · listings · land and product bids · profiles · chat history · file uploads · email · scheduled auction processing'], ['MongoDB Atlas', 'Users · Lands · Products · Bids · Chats'], ['Multer images', 'Nodemailer reset', 'node-cron schedules', 'PDFKit certificates', 'Socket.IO chat delivery']],
  ['Authentication', ['Email/password sign-up or Google sign-in integration', 'bcrypt hashes email-based passwords', 'Backend verifies credentials and issues a one-hour JWT'], ['Frontend stores and attaches token to protected requests', 'Middleware verifies token and retrieves user', 'Socket.IO uses the token for authenticated socket connections'], ['Password-reset requests generate a time-limited email link'], []],
  ['Bidding', ['User opens a land or agricultural-product auction', 'Interface shows current amount, timing and bid information', 'User sends a JWT-authenticated bid request'], ['Backend verifies the user and auction', 'Land owners cannot bid on their own land listing', 'Bid is persisted and highest amount updates when applicable'], ['Database-backed bid records provide dynamic updates and feedback'], ['Concurrency improvement: Production bidding should use an atomic conditional update or transaction so simultaneous bidders cannot overwrite one another or submit a stale amount.']],
  ['Auction Completion', ['node-cron runs every minute', 'Expired ongoing land auctions are found', 'Highest land bid is retrieved'], ['Highest bidder is selected when a valid bid exists', 'PDFKit generates a winner certificate', 'Land record receives completed status, winner ID, final amount, time and certificate path'], ['No-bid land auctions complete without a winner', 'Winners can access completed land-auction information and certificate'], []],
  ['Real-Time Chat', ['User opens chat from a property page', 'Previous messages are retrieved', 'Socket.IO connects using the user JWT'], ['Sender emits a send_message event', 'Backend stores message in MongoDB', 'Message emits to the receiver socket room'], ['Online receivers see messages immediately', 'Offline receivers receive the persisted conversation on return'], []],
]

const capabilities = ['Land listing management', 'Agricultural-product listings', 'Land and product bidding', 'Search and discovery', 'Real-time communication', 'User dashboard', 'Automated land-auction processing', 'Password recovery', 'Role-aware navigation', 'Admin foundation']
const featureList = ['Email and password registration', 'Google sign-in integration', 'bcrypt password hashing', 'JWT-based authentication', 'One-hour token expiry', 'Password-reset email workflow', 'Land listing creation', 'Multiple-image uploads', 'Edit and delete owned land listings', 'Agricultural-product creation', 'Paginated product browsing', 'Land and product bid records', 'Protection against bidding on owned land', 'Land search by location and type', 'My Listings', 'My Bids', 'My Wins', 'User profile management', 'Socket.IO chat', 'Persisted messages', 'Scheduled land-auction completion', 'Automated winner identification', 'PDF winner certificates', 'Responsive interface', 'Toast-based user feedback']
const challenges = [['Coordinating live communication', 'Socket.IO provides event delivery, authenticated socket rooms identify connected users and MongoDB stores conversation history.', 'Real-time delivery and persistence are separate responsibilities and both must be handled.'], ['Processing expired auctions', 'A node-cron task checks expired auctions, retrieves the highest bid, updates the auction and generates a certificate.', 'Background workflows require idempotency, failure handling and careful status transitions.'], ['Managing concurrent bids', 'Bid requests are validated and persisted through the backend while the current amount updates in the database.', 'Production should use atomic conditional updates, transactions or optimistic concurrency control to prevent race conditions.'], ['Handling multiple images', 'Multer processes multipart requests, generates filenames and stores accessible paths.', 'Production uploads also need validation, limits, cleanup and durable cloud storage.'], ['Maintaining authentication state', 'Context API manages frontend identity while JWT middleware protects backend operations.', 'Authentication rules must be consistent across HTTP and WebSocket channels.'], ['Connecting deployed origins', 'CORS and Socket.IO were configured for recognised frontend origins.', 'Environment-specific origins and API URLs should be centralised through environment variables.'], ['Search implementation', 'MongoDB case-insensitive matching searches location and land-type fields.', 'Regex search suits a prototype; indexes or dedicated search are preferable at scale.'], ['Organising a large full-stack codebase', 'Backend logic is separated into routes, controllers, models, middleware and utilities.', 'Separation of concerns makes complex applications easier to maintain.']]

function Section({ title, children, tone = '' }) { return <section className={`ag-section ${tone}`}><h3>{title}</h3>{children}</section> }

function WorkflowTabs() {
  const [active, setActive] = useState(0)
  const [label, client, api, data, services] = tabs[active]
  return <div className="ag-workflow"><div className="ag-tabs" role="tablist" aria-label="Agri-Products architecture workflows">{tabs.map(([tab], index) => <button type="button" role="tab" aria-selected={active === index} className={active === index ? 'ag-tab-active' : ''} onClick={() => setActive(index)} key={tab}>{tab}</button>)}</div><div className="ag-workflow-panel" role="tabpanel"><p className="ag-workflow-label">{label} workflow</p><div className="ag-flow-grid"><article><h4>Client / trigger</h4>{client.map((item) => <p key={item}>{item}</p>)}</article><i aria-hidden="true">→</i><article><h4>API / processing</h4>{api.map((item) => <p key={item}>{item}</p>)}</article><i aria-hidden="true">→</i><article><h4>Data / outcome</h4>{data.map((item) => <p key={item}>{item}</p>)}</article></div>{services.length > 0 && <aside>{services.map((item) => <span key={item}>{item}</span>)}</aside>}</div></div>
}

function AgriProductsCaseStudy({ project }) {
  const metadata = [['Domain', 'Agriculture and Marketplace'], ['Project type', 'Full-Stack Web Application'], ['Development period', '2024–2025'], ['Status', <span className="ag-status-badge" key="status-badge"><span aria-hidden="true" />Full-Stack Prototype · Deployment Temporarily Unavailable</span>], ['Frontend', 'React'], ['Backend', 'Node.js and Express'], ['Database', 'MongoDB Atlas']]
  return <div className="ag-case-study">
    <section className="ag-hero"><p>FULL-STACK AGRICULTURAL MARKETPLACE</p><h2 id="project-modal-title">Agri-Products</h2><h3>Connecting agricultural land and product listings with competitive auctions, automated winner processing and real-time buyer–seller communication.</h3><div className="ag-hero-copy"><p id="project-modal-overview">Agri-Products is a full-stack agricultural marketplace created to provide a more organised and transparent way to list agricultural land and products, participate in auctions and communicate directly with sellers.</p><p>The platform combines land and product listings, time-bound bidding, user authentication, real-time chat, search, bid tracking and automated land-auction completion in one connected application. It demonstrates how React, Express, MongoDB and Socket.IO can support a practical marketplace workflow.</p></div><div className="ag-hero-badges" aria-label="Core technologies">{['React', 'Node.js', 'Express', 'MongoDB', 'Socket.IO'].map((technology) => <span key={technology}>{technology}</span>)}</div><dl className="ag-metadata">{metadata.map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><ProjectLinks links={project.links} variant="modal" /><p className="ag-deployment-note"><b>Deployment note:</b> The project’s source code and complete case study are currently available through GitHub. The public demo has been temporarily removed because the backend service is unavailable. It can be restored after the backend deployment is fixed and verified.</p></section>
    <Section title="Technology Stack"><div className="ag-stack-grid"><article><h4>Frontend</h4><p>React 19 · React Router 7 · Context API · Axios · Socket.IO Client · React Toastify · Lucide React and React Icons · responsive CSS-based interfaces.</p></article><article><h4>Backend</h4><p>Node.js · Express · MongoDB with Mongoose · Socket.IO · JSON Web Tokens · bcrypt · Multer · Nodemailer · node-cron · PDFKit · CORS · dotenv.</p></article></div><div className="ag-collection-grid">{['Users', 'Lands', 'Products', 'Bids', 'Product Bids', 'Chats', 'Token Blacklist'].map((item) => <span key={item}>{item}</span>)}</div><p className="ag-note">A modular client-server application with an Express backend—not a microservices architecture.</p></Section>
    <Section title="Deployment Architecture"><ul className="ag-deployment-architecture"><li><b>Frontend deployment target:</b> Netlify</li><li><b>Backend deployment target:</b> Render</li><li><b>Database:</b> MongoDB Atlas</li><li><b>Current availability:</b> Temporarily offline</li></ul></Section>
    <Section title="Architecture / Workflow"><WorkflowTabs /></Section>
    <Section title="Problem" tone="ag-problem"><p>Agricultural trading is often affected by limited market reach, fragmented communication and a lack of transparent price discovery. Farmers and sellers may depend heavily on nearby buyers or informal networks, making it difficult to compare offers and reach a broader audience.</p><p>Manual auction management introduces additional difficulties. Bids can be hard to track, winners may be announced late and transaction-related information may not be stored consistently. Buyers and sellers may also depend on calls or disconnected messaging tools when discussing a listing.</p><p>Agri-Products explores how a digital marketplace could address these challenges by connecting listings, auctions, search, user accounts and direct communication in one system.</p><div className="ag-problem-grid">{['Limited access to potential buyers', 'Inconsistent price discovery', 'Fragmented buyer–seller communication', 'Manual bid tracking', 'Delayed winner determination', 'Difficulty discovering relevant listings', 'Lack of consolidated bidding history', 'Limited documentation for auction outcomes'].map((item) => <span key={item}>{item}</span>)}</div><strong className="ag-highlight">Design objective: Build a connected agricultural marketplace where users can discover listings, place competitive bids, communicate directly and track auction activity from one platform.</strong></Section>
    <Section title="Solution" tone="ag-solution"><p>Agri-Products was developed as a modular full-stack application with a React client, an Express API, MongoDB persistence and Socket.IO-based messaging.</p><p>The platform supports both agricultural land and product listings. Users can create listings with images, location information, starting amounts and auction timing. Other authenticated users can explore available listings, view details and participate in bidding.</p><p>The application also provides user-focused pages for managing listings, reviewing bids and viewing completed land auctions won by the user. Real-time chat enables direct communication, while scheduled backend processing handles expired land auctions and generates winner certificates.</p><div className="ag-feature-grid">{capabilities.map((item) => <article key={item}><h4>{item}</h4><p>{item === 'Admin foundation' ? 'The application contains an Admin role and an initial protected Admin dashboard interface; expanded administration remains planned work.' : 'Implemented as part of the connected marketplace workflow, using the shared React, Express and MongoDB application layers.'}</p></article>)}</div></Section>
    <Section title="Key Features"><div className="ag-feature-list">{featureList.map((item) => <span key={item}>{item}</span>)}</div><p className="ag-note">Token blacklisting is not presented as fully enforced until authentication middleware checks the blacklist on every protected request.</p></Section>
    <Section title="Challenges and Engineering Decisions"><div className="ag-challenge-grid">{challenges.map(([title, approach, learning], index) => <details key={title} open={index === 0}><summary><span>{String(index + 1).padStart(2, '0')}</span>{title}</summary><p><b>Approach:</b> {approach}</p><p><b>Learning:</b> {learning}</p></details>)}</div></Section>
    <Section title="Lessons Learned"><div className="ag-lesson-grid">{['Real-time applications need two forms of state', 'Client-side validation is not sufficient', 'Scheduled workflows need reliability controls', 'Database design affects bidding logic', 'Authentication must cover every transport', 'Upload handling extends beyond receiving files', 'Deployment configuration belongs in the environment', 'Honest product status builds credibility'].map((title) => <article key={title}><h4>{title}</h4><p>Strong marketplace engineering requires coordinated client, backend, database and operational decisions rather than isolated features.</p></article>)}</div><strong className="ag-highlight">Key takeaway: Agri-Products strengthened my understanding of full-stack architecture, database-backed auctions, authenticated real-time communication, background processing and the engineering trade-offs involved in building a multi-user marketplace.</strong></Section>
    <Section title="Key Achievements"><div className="ag-achievement-grid">{['Built connected land and agricultural-product listing workflows', 'Implemented both land and product bid persistence', 'Added authenticated real-time messaging with Socket.IO', 'Preserved chat history in MongoDB', 'Created scheduled land-auction completion', 'Generated downloadable PDF winner certificates', 'Added user-specific listings, bids and wins', 'Implemented email/password and Google sign-in workflows', 'Deployed the frontend and backend to separate cloud platforms', 'Organised the backend into routes, controllers, models, middleware and utilities'].map((item) => <span key={item}>{item}</span>)}</div></Section>
    <Section title="Engineering Status" tone="ag-status"><div className="ag-status-grid"><article><h4>Verified capabilities</h4><ul>{['Deployed React frontend target', 'Express and MongoDB backend', 'Land and product listings', 'JWT-based authentication', 'Password hashing', 'User-specific bid records', 'Socket.IO chat', 'MongoDB chat persistence', 'Scheduled land-auction processing', 'PDF winner certificates', 'Search and profile workflows'].map((item) => <li key={item}>{item}</li>)}</ul></article><article><h4>Production hardening</h4><ul>{['Resolve all Git merge-conflict markers', 'Centralise API URLs in environment configuration', 'Enforce token-blacklist checks in authentication middleware', 'Verify Google credentials server-side', 'Protect chat-history endpoints', 'Apply consistent server-side bid validation', 'Use atomic bid updates', 'Expand and secure admin APIs', 'Add upload type and size validation', 'Move media to durable cloud storage', 'Add rate limiting and structured validation', 'Add automated tests, monitoring and retry-safe scheduled processing'].map((item) => <li key={item}>{item}</li>)}</ul></article></div></Section>
    <Section title="Future Enhancements"><div className="ag-future-grid">{['Razorpay or Stripe payment integration', 'Advanced auction and market analytics', 'Price forecasting', 'Personalised listing recommendations', 'Regional-language support', 'Map-based discovery and geolocation search', 'Seller KYC and verification', 'Rating and review system', 'Mobile applications and push notifications', 'Notification service for bid changes and auction results', 'Expanded admin management', 'Cloud object storage for images and certificates', 'Transaction-safe concurrent bidding'].map((item) => <span key={item}>{item}</span>)}</div></Section><div className="ag-footer-action"><ProjectLinks links={project.links} variant="modal" /></div>
  </div>
}

export default AgriProductsCaseStudy
